-----------------
CREATE TABLE PROFESORES 
(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(30),
	APELLIDO VARCHAR(30),
	DESPACHO VARCHAR(3),
	TELEFONO VARCHAR(9),
	CONSTRAINT PK_DNI PRIMARY KEY(DNI),
	CONSTRAINT U_TEL UNIQUE(TELEFONO),
	CONSTRAINT CH_DNI CHECK(DNI RLIKE '[0-9]{8}[A-Z]' OR DNI RLIKE '[K,L,M,X,Y,Z][0-9]{7}[A-Z]')
);

-----------------


CREATE TABLE NO_DOCTORES
(
	DNI VARCHAR(9),
	CONSTRAINT FK_DNI FOREIGN KEY(DNI) REFERENCES PROFESORES(DNI),
	CONSTRAINT PK_DNINO PRIMARY KEY(DNI)
);

-----------------

CREATE TABLE DOCTORES
(
	DNI VARCHAR(9),
	TITULACION VARCHAR(80),
	ESPECIALIDAD VARCHAR(100),
	FECHA_DOCTORADO DATE,
	TITULO_TESIS VARCHAR(250),
	CONSTRAINT FK_DNIDOC FOREIGN KEY(DNI) REFERENCES PROFESORES(DNI),
	CONSTRAINT PK_DNIDOC PRIMARY KEY(DNI),
	CONSTRAINT CH_TITUL CHECK(TITULACION LIKE 'LICENCIADO EN%' OR TITULACION LIKE 'INGENIERO%' OR TITULACION LIKE 'GRADO EN%')
);

-----------------

CREATE TABLE SUPERVISIONES
(
	CODIGO INTEGER,
	DNINODOCTOR VARCHAR(9),
	DNIDOCTOR VARCHAR(9),
	FECHAINI DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_DNISUP PRIMARY KEY(DNINODOCTOR,DNIDOCTOR,FECHAINI),
	CONSTRAINT FK_DNINOD FOREIGN KEY(DNINODOCTOR) REFERENCES NO_DOCTORES(DNI)
);

-----------------

CREATE TABLE PROYECTOS_DE_INVESTIGACION
(
	CODIGO VARCHAR(7),
	DNI_RESPONSABLE VARCHAR(9),
	NOMBRE VARCHAR(100),
	ACRONIMO VARCHAR(4),
	PRESUPUESTO NUMERIC(20),
	FECHAINI DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_CODP PRIMARY KEY(CODIGO),
	CONSTRAINT FK_DNIRES FOREIGN KEY(DNI_RESPONSABLE) REFERENCES DOCTORES(DNI),
	CONSTRAINT CH_CODP CHECK(CODIGO RLIKE '[A-Z][0-9]{4}-[A-Z]'),
	CONSTRAINT CH_CODRI1 CHECK(LENGTH(ACRONIMO) = 3 OR LENGTH(ACRONIMO) = 4)
);

-----------------

CREATE TABLE ANTECEDENTES
(
	CODIGO_PROYECTO_ANTIGUO VARCHAR(7),
	CODIGO_PROYECTO_NUEVO VARCHAR(7),
	CONSTRAINT PK_CODANT PRIMARY KEY(CODIGO_PROYECTO_ANTIGUO,CODIGO_PROYECTO_NUEVO),
	CONSTRAINT FK_CODANT1 FOREIGN KEY(CODIGO_PROYECTO_ANTIGUO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO),
	CONSTRAINT FK_CODANT2 FOREIGN KEY(CODIGO_PROYECTO_NUEVO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO)
);

-----------------

CREATE TABLE OBJETIVOS
(
	CODIGO VARCHAR(4),
	CODIGOPROYECTO VARCHAR(7),
	NOMBRE VARCHAR(50),
	DESCRIPCION VARCHAR(120),
	CONSTRAINT PK_CODOBJ PRIMARY KEY(CODIGO),
	CONSTRAINT FK_CODOBJ FOREIGN KEY(CODIGOPROYECTO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO)
);

-----------------

CREATE TABLE CRITERIOS
(
	CODIGO VARCHAR(4),
	CODOBJETIVO VARCHAR(4),
	DESCRIPCION VARCHAR(120),
	CONSTRAINT PK_CODCRI PRIMARY KEY(CODIGO,CODOBJETIVO),
	CONSTRAINT FK_CODCRI FOREIGN KEY(CODOBJETIVO) REFERENCES OBJETIVOS(CODIGO)
);

-----------------

CREATE TABLE EVALUADORES
(
	CODIGO VARCHAR(3),
	NOMBRE VARCHAR(30),
	APELLIDO VARCHAR(50),
	TELEFONO VARCHAR(9),
	CONSTRAINT PK_CODEVAL PRIMARY KEY(CODIGO),
	CONSTRAINT U_TELEVA UNIQUE(TELEFONO),
	CONSTRAINT CH_TEL CHECK(TELEFONO IS NOT NULL),
	CONSTRAINT CH_COD CHECK(CODIGO RLIKE '^[A-Z0-9]*')
);

-----------------

CREATE TABLE VALORACIONES
(
	CODOBJETIVO VARCHAR(4),
	CODCRITERIO VARCHAR(4),
	CODEVALUADOR VARCHAR(3),
	FECHA DATE,
	VALORACION VARCHAR(30),
	CONSTRAINT PK_CODVAL PRIMARY KEY(CODOBJETIVO,CODCRITERIO,CODEVALUADOR,FECHA),
	CONSTRAINT FK_CODVAL1 FOREIGN KEY(CODCRITERIO,CODOBJETIVO) REFERENCES CRITERIOS(CODIGO,CODOBJETIVO),
	CONSTRAINT FK_CODVAL2 FOREIGN KEY(CODEVALUADOR) REFERENCES EVALUADORES(CODIGO),
	CONSTRAINT CH_VAL CHECK(VALORACION IN('CUMPLIDO', 'TEMPORALMENTE NO EVALUABLE') OR TO_NUMBER(VALORACION) BETWEEN '0' AND '100'),
	CONSTRAINT CH_DATE CHECK(TO_CHAR(FECHA,'MM/DD') NOT BETWEEN '06/22' AND '09/22')
);

-----------------

CREATE TABLE COLABORACIONES
(
	DNICOLABORADOR VARCHAR(9),
	CODIGOPROYECTO VARCHAR(7),
	FECHAINI DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_DNICOL PRIMARY KEY(DNICOLABORADOR,CODIGOPROYECTO,FECHAINI),
	CONSTRAINT FK_DNICOL1 FOREIGN KEY(DNICOLABORADOR) REFERENCES NO_DOCTORES(DNI),
	CONSTRAINT FK_DNICOL2 FOREIGN KEY(CODIGOPROYECTO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO),
	CONSTRAINT CH_DATECOL CHECK((TO_CHAR(FECHAINI, 'DD') BETWEEN '01' AND '07') AND (TO_CHAR(FECHAINI, 'DD') LIKE '%LUNES%'))
);
