-----------------
CREATE TABLE PROFESORES 
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(30),
	APELLIDO VARCHAR2(30),
	DESPACHO VARCHAR2(3),
	TELEFONO VARCHAR2(9),
	CONSTRAINT PK_DNI PRIMARY KEY(DNI),
	CONSTRAINT U_TEL UNIQUE(TELEFONO),
	CONSTRAINT CH_DNI CHECK(REGEXP_LIKE(DNI,'[0-9]{8}[A-Z]') OR REGEXP_LIKE(DNI,'[K,L,M,X,Y,Z][0-9]{7}[A-Z]'))
);

-----------------


CREATE TABLE NO_DOCTORES
(
	DNI VARCHAR2(9),
	CONSTRAINT FK_DNI FOREIGN KEY(DNI) REFERENCES PROFESORES(DNI),
	CONSTRAINT PK_DNINO PRIMARY KEY(DNI)
);

-----------------

CREATE TABLE DOCTORES
(
	DNI VARCHAR2(9),
	TITULACION VARCHAR2(80),
	ESPECIALIDAD VARCHAR2(100),
	FECHA_DOCTORADO DATE,
	TITULO_TESIS VARCHAR2(250),
	CONSTRAINT FK_DNIDOC FOREIGN KEY(DNI) REFERENCES PROFESORES(DNI),
	CONSTRAINT PK_DNIDOC PRIMARY KEY(DNI),
	CONSTRAINT CH_TITUL CHECK(TITULACION LIKE 'LICENCIADO EN%' OR TITULACION LIKE 'INGENIERO%' OR TITULACION LIKE 'GRADO EN%')
);

-----------------

CREATE TABLE SUPERVISIONES
(
	DNINODOCTOR	VARCHAR2(9),
	DNIDOCTOR	VARCHAR2(9),
	FECHAINI	DATE,
	FECHAFIN	DATE,
	CONSTRAINT PK_DNISUP PRIMARY KEY(DNINODOCTOR,DNIDOCTOR,FECHAINI),
	CONSTRAINT FK_DNINOD FOREIGN KEY(DNINODOCTOR) REFERENCES NO_DOCTORES(DNI)
);

-----------------

CREATE TABLE PROYECTOS_DE_INVESTIGACION
(
	CODIGO VARCHAR2(7),
	DNI_RESPONSABLE VARCHAR2(9),
	NOMBRE VARCHAR2(100),
	ACRONIMO VARCHAR2(4),
	PRESUPUESTO NUMBER(20),
	FECHAINI DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_CODP PRIMARY KEY(CODIGO),
	CONSTRAINT FK_DNIRES FOREIGN KEY(DNI_RESPONSABLE) REFERENCES DOCTORES(DNI),
	CONSTRAINT CH_CODP CHECK(REGEXP_LIKE(CODIGO, '[A-Z][0-9]{4}-[A-Z]')),
	CONSTRAINT CH_CODRI1 CHECK(LENGTH(ACRONIMO) = 3 OR LENGTH(ACRONIMO) = 4)
);

-----------------

CREATE TABLE ANTECEDENTES
(
	CODIGO_PROYECTO_ANTIGUO VARCHAR2(7),
	CODIGO_PROYECTO_NUEVO VARCHAR2(7),
	CONSTRAINT PK_CODANT PRIMARY KEY(CODIGO_PROYECTO_ANTIGUO,CODIGO_PROYECTO_NUEVO),
	CONSTRAINT FK_CODANT1 FOREIGN KEY(CODIGO_PROYECTO_ANTIGUO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO),
	CONSTRAINT FK_CODANT2 FOREIGN KEY(CODIGO_PROYECTO_NUEVO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO)
);

-----------------

CREATE TABLE OBJETIVOS
(
	CODIGO VARCHAR2(4),
	CODIGOPROYECTO VARCHAR2(7),
	NOMBRE VARCHAR2(50),
	DESCRIPCION VARCHAR2(120),
	CONSTRAINT PK_CODOBJ PRIMARY KEY(CODIGO),
	CONSTRAINT FK_CODOBJ FOREIGN KEY(CODIGOPROYECTO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO)
);

-----------------

CREATE TABLE CRITERIOS
(
	CODIGO VARCHAR2(4),
	CODOBJETIVO	VARCHAR2(4),
	DESCRIPCION	VARCHAR2(120),
	CONSTRAINT PK_CODCRI PRIMARY KEY(CODIGO,CODOBJETIVO),
	CONSTRAINT FK_CODCRI FOREIGN KEY(CODOBJETIVO) REFERENCES OBJETIVOS(CODIGO)
);

-----------------

CREATE TABLE EVALUADORES
(
	CODIGO VARCHAR2(3),
	NOMBRE VARCHAR2(30),
	APELLIDO VARCHAR2(50),
	TELEFONO VARCHAR2(9),
	CONSTRAINT PK_CODEVAL PRIMARY KEY(CODIGO),
	CONSTRAINT U_TELEVA UNIQUE(TELEFONO),
	CONSTRAINT CH_TEL CHECK(TELEFONO IS NOT NULL),
	CONSTRAINT CH_COD CHECK(REGEXP_LIKE(CODIGO, '^[A-Z0-9]*'))
);

-----------------

CREATE TABLE VALORACIONES
(
	CODOBJETIVO VARCHAR2(4),
	CODCRITERIO VARCHAR2(4),
	CODEVALUADOR VARCHAR2(3),
	FECHA DATE,
	VALORACION VARCHAR2(30),
	CONSTRAINT PK_CODVAL PRIMARY KEY(CODOBJETIVO,CODCRITERIO,CODEVALUADOR,FECHA),
	CONSTRAINT FK_CODVAL1 FOREIGN KEY(CODCRITERIO,CODOBJETIVO) REFERENCES CRITERIOS(CODIGO,CODOBJETIVO),
	CONSTRAINT FK_CODVAL2 FOREIGN KEY(CODEVALUADOR) REFERENCES EVALUADORES(CODIGO),
	CONSTRAINT CH_VAL CHECK(VALORACION IN('CUMPLIDO', 'TEMPORALMENTE NO EVALUABLE') OR TO_NUMBER(VALORACION) BETWEEN '0' AND '100'),
	CONSTRAINT CH_DATE CHECK(TO_CHAR(FECHA,'MM/DD') NOT BETWEEN '06/22' AND '09/22')
);

-----------------

CREATE TABLE COLABORACIONES
(
	DNICOLABORADOR VARCHAR2(9),
	CODIGOPROYECTO VARCHAR2(7),
	FECHAINI DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_DNICOL PRIMARY KEY(DNICOLABORADOR,CODIGOPROYECTO,FECHAINI),
	CONSTRAINT FK_DNICOL1 FOREIGN KEY(DNICOLABORADOR) REFERENCES NO_DOCTORES(DNI),
	CONSTRAINT FK_DNICOL2 FOREIGN KEY(CODIGOPROYECTO) REFERENCES PROYECTOS_DE_INVESTIGACION(CODIGO),
	CONSTRAINT CH_DATECOL CHECK((TO_CHAR(FECHAINI, 'DD') BETWEEN '01' AND '07') AND (TO_CHAR(FECHAINI, 'DAY') LIKE '%LUNES%'))
);

