# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define :servidor do |servidor|
  servidor.vm.box = "buster"
  servidor.vm.hostname = "jesus"
  servidor.vm.network :public_network,:bridge=>"wlan0"
  servidor.vm.network :private_network, ip: "10.0.0.100",
    virtualbox__intnet: "bind9"
end

config.vm.define :cliente do |cliente|
  cliente.vm.box = "buster"
  cliente.vm.hostname = "clientebind9"
  cliente.vm.network :private_network, type: "dhcp",
    virtualbox__intnet: "bind9"
end

config.vm.define :cliente2 do |cliente2|
  cliente2.vm.box = "buster"
  cliente2.vm.hostname = "cliente2bind9"
  cliente2.vm.network :private_network, type: "dhcp",
    virtualbox__intnet: "bind9"
end

config.vm.define :correo do |correo|
  correo.vm.box = "buster"
  correo.vm.hostname = "correo"
  correo.vm.network :private_network, ip: "10.0.0.200",
    virtualbox__intnet: "bind9"
end

config.vm.define :ftp do |ftp|
  ftp.vm.box = "buster"
  ftp.vm.hostname = "ftp"
  ftp.vm.network :private_network, ip: "10.0.0.201",
    virtualbox__intnet: "bind9"
end

config.vm.define :web do |web|
  web.vm.box = "buster"
  web.vm.hostname = "web"
  web.vm.network :private_network, ip: "10.0.0.202",
    virtualbox__intnet: "bind9"
end

# Configuración adicional master/slave
config.vm.define :servidor2 do |servidor2|
  servidor2.vm.box = "buster"
  servidor2.vm.hostname = "jesus-slave"
  servidor2.vm.network :private_network, ip: "10.0.0.101",
    virtualbox__intnet: "bind9"
end

# Configuración adicional Subdominio
config.vm.define :servidor3 do |servidor3|
  servidor3.vm.box = "buster"
  servidor3.vm.hostname = "jesus-subd"
  servidor3.vm.network :private_network, ip: "10.0.0.102",
    virtualbox__intnet: "bind9"
end
end