Vagrant.configure("2") do |config|

#----- Masters -----#
config.vm.define :master1 do |master1|
  master1.vm.box = "ubuntu/bionic64"
  config.vm.provider "resources" do |r|
    r.memory = 768
	r.cpus = 2
  end
  master1.vm.hostname = "k8s-master1"
  master1.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: "k8s-masters"
  master1.vm.network :private_network, ip: "192.168.1.10", virtualbox__intnet: "k8s-agents"
end

config.vm.define :master2 do |master2|
  master2.vm.box = "ubuntu/bionic64"
  config.vm.provider "resources" do |r|
    r.memory = 768
	r.cpus = 2
  end
  master2.vm.hostname = "k8s-master2"
  master2.vm.network :private_network, ip: "10.0.0.11", virtualbox__intnet: "k8s-masters"
  master2.vm.network :private_network, ip: "192.168.1.11", virtualbox__intnet: "k8s-agents"
end
#-------------------#

#----- Agents -----#
config.vm.define :agent1 do |agent1|
  agent1.vm.box = "ubuntu/bionic64"
  config.vm.provider "resources" do |r|
    r.memory = 768
	r.cpus = 2
  end
  agent1.vm.hostname = "k8s-agent1"
  agent1.vm.network :private_network, ip: "192.168.1.20", virtualbox__intnet: "k8s-agents"
end

config.vm.define :agent2 do |agent2|
  agent2.vm.box = "ubuntu/bionic64"
  config.vm.provider "resources" do |r|
    r.memory = 768
	r.cpus = 2
  end
  agent2.vm.hostname = "k8s-agent2"
  agent2.vm.network :private_network, ip: "192.168.1.21", virtualbox__intnet: "k8s-agents"
end

config.vm.define :agent3 do |agent3|
  agent3.vm.box = "ubuntu/bionic64"
  config.vm.provider "resources" do |r|
    r.memory = 768
	r.cpus = 2
  end
  agent3.vm.hostname = "k8s-agent3"
  agent3.vm.network :private_network, ip: "192.168.1.22", virtualbox__intnet: "k8s-agents"
end

config.vm.define :agent4 do |agent4|
  agent4.vm.box = "ubuntu/bionic64"
  config.vm.provider "resources" do |r|
    r.memory = 768
	r.cpus = 2
  end
  agent4.vm.hostname = "k8s-agent4"
  agent4.vm.network :private_network, ip: "192.168.1.23", virtualbox__intnet: "k8s-agents"
end
#------------------#

#----- Clients -----#
config.vm.define :client do |client|
  client.vm.box = "ubuntu/bionic64"
  client.vm.hostname = "k8s-client"
  client.vm.network :private_network, ip: "192.168.1.30", virtualbox__intnet: "k8s-agents"
end
#-------------------#
end